spring:
 datasource:
  driver-class-name:  org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/mercari-data
  username: postgres
  password: postgres
server:
 servlet:
  context-path: /mercari-data
