spring:
 security:
  user:
   # https://docs.spring.io/spring-boot/docs/3.0.1/reference/htmlsingle/#application-properties.security.spring.security.user.name
   name: admin.ziro@rakus-partners.co.jp
   password: Aaaaa123
 datasource:
  driver-class-name:  org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/mercari
  username: postgres
  password: postgres
#  batch:
#    jdbc:
#      initialize-schema: always
server:
 servlet:
  context-path: /mercari-data
